export const CLEAR_TODO = 'CLEAR_TODO';

export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'LOAD_BOOKS_FAILURE';
export const LOAD_BOOKS_REQUEST = 'LOAD_BOOKS_REQUEST';
