export const ADD_TODO = 'ADD_TODO';
export const TOGGLE_CHECKED = 'TOGGLE_CHECKED';
export const DELETE_TODO = 'DELETE_TODO';
export const SET_FILTER = 'SET_FILTER';
export const CLEAR_TODO = 'CLEAR_TODO';

export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_BOOKS_FAILURE = 'LOAD_BOOKS_FAILURE';
export const LOAD_BOOKS_REQUEST = 'LOAD_BOOKS_REQUEST';

export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHORS_FAILURE = 'LOAD_AUTHORS_FAILURE';
export const LOAD_AUTHORS_REQUEST = 'LOAD_AUTHORS_REQUEST';
